
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Button btnAdmin;

	private global::Gtk.Button btnEmpleado;

	private global::Gtk.Button btnSalir;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnAdmin = new global::Gtk.Button();
		this.btnAdmin.CanFocus = true;
		this.btnAdmin.Name = "btnAdmin";
		this.btnAdmin.UseUnderline = true;
		this.btnAdmin.Label = global::Mono.Unix.Catalog.GetString("Administrador");
		this.vbox1.Add(this.btnAdmin);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnAdmin]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnEmpleado = new global::Gtk.Button();
		this.btnEmpleado.CanFocus = true;
		this.btnEmpleado.Name = "btnEmpleado";
		this.btnEmpleado.UseUnderline = true;
		this.btnEmpleado.Label = global::Mono.Unix.Catalog.GetString("Empleado");
		this.vbox1.Add(this.btnEmpleado);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnEmpleado]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnSalir = new global::Gtk.Button();
		this.btnSalir.CanFocus = true;
		this.btnSalir.Name = "btnSalir";
		this.btnSalir.UseUnderline = true;
		this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.vbox1.Add(this.btnSalir);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnSalir]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnAdmin.Clicked += new global::System.EventHandler(this.OnBtnAdminClicked);
	}
}
