
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEmpleadosEyS
{
	public partial class GestionDepartamentos
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.Label lbDep;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label lblID;

		private global::Gtk.Entry txtId;

		private global::Gtk.Table table1;

		private global::Gtk.Label lbDep1;

		private global::Gtk.Label lbEmail;

		private global::Gtk.Label lbExt;

		private global::Gtk.Entry txtDep;

		private global::Gtk.Entry txtEmail;

		private global::Gtk.Entry txtExt;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.Button BtnEditar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvDepartamento;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEmpleadosEyS.GestionDepartamentos
			this.Name = "SistemaEmpleadosEyS.GestionDepartamentos";
			this.Title = global::Mono.Unix.Catalog.GetString("GestionDepartamentos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SistemaEmpleadosEyS.GestionDepartamentos.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lbDep = new global::Gtk.Label();
			this.lbDep.Name = "lbDep";
			this.lbDep.LabelProp = global::Mono.Unix.Catalog.GetString("Gestion de Departamentos");
			this.vbox3.Add(this.lbDep);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.lbDep]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblID = new global::Gtk.Label();
			this.lblID.Name = "lblID";
			this.lblID.LabelProp = global::Mono.Unix.Catalog.GetString("ID:");
			this.hbox3.Add(this.lblID);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblID]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtId = new global::Gtk.Entry();
			this.txtId.CanFocus = true;
			this.txtId.Name = "txtId";
			this.txtId.IsEditable = true;
			this.txtId.InvisibleChar = '•';
			this.hbox3.Add(this.txtId);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtId]));
			w3.Position = 1;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.lbDep1 = new global::Gtk.Label();
			this.lbDep1.Name = "lbDep1";
			this.lbDep1.LabelProp = global::Mono.Unix.Catalog.GetString("Departamento:");
			this.table1.Add(this.lbDep1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.lbDep1]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbEmail = new global::Gtk.Label();
			this.lbEmail.Name = "lbEmail";
			this.lbEmail.LabelProp = global::Mono.Unix.Catalog.GetString("Email:");
			this.table1.Add(this.lbEmail);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.lbEmail]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbExt = new global::Gtk.Label();
			this.lbExt.Name = "lbExt";
			this.lbExt.LabelProp = global::Mono.Unix.Catalog.GetString("Extensión:");
			this.table1.Add(this.lbExt);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.lbExt]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtDep = new global::Gtk.Entry();
			this.txtDep.CanFocus = true;
			this.txtDep.Name = "txtDep";
			this.txtDep.IsEditable = true;
			this.txtDep.InvisibleChar = '•';
			this.table1.Add(this.txtDep);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.txtDep]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtEmail = new global::Gtk.Entry();
			this.txtEmail.CanFocus = true;
			this.txtEmail.Name = "txtEmail";
			this.txtEmail.IsEditable = true;
			this.txtEmail.InvisibleChar = '•';
			this.table1.Add(this.txtEmail);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.txtEmail]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtExt = new global::Gtk.Entry();
			this.txtExt.CanFocus = true;
			this.txtExt.Name = "txtExt";
			this.txtExt.IsEditable = true;
			this.txtExt.InvisibleChar = '•';
			this.table1.Add(this.txtExt);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.txtExt]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add(this.table1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.table1]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbox2.Add(this.btnGuardar);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnGuardar]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.BtnEditar = new global::Gtk.Button();
			this.BtnEditar.CanFocus = true;
			this.BtnEditar.Name = "BtnEditar";
			this.BtnEditar.UseUnderline = true;
			this.BtnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.hbox2.Add(this.BtnEditar);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.BtnEditar]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.hbox2.Add(this.btnEliminar);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnEliminar]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox3.Add(this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvDepartamento = new global::Gtk.TreeView();
			this.tvDepartamento.CanFocus = true;
			this.tvDepartamento.Name = "tvDepartamento";
			this.GtkScrolledWindow.Add(this.tvDepartamento);
			this.vbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w17.Position = 4;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.btnGuardar.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.BtnEditar.Clicked += new global::System.EventHandler(this.OnBtnEditarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.tvDepartamento.CursorChanged += new global::System.EventHandler(this.OnTvDepartamentoCursorChanged);
		}
	}
}
