
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEmpleadosEyS
{
	public partial class MenuAdministrador
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Button btnGestion;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnCargos;

		private global::Gtk.Button btnDep;

		private global::Gtk.Button btnCarEmpleado;

		private global::Gtk.Button btnReporte1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEmpleadosEyS.MenuAdministrador
			this.Name = "SistemaEmpleadosEyS.MenuAdministrador";
			this.Title = global::Mono.Unix.Catalog.GetString("MenuAdministrador");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SistemaEmpleadosEyS.MenuAdministrador.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnGestion = new global::Gtk.Button();
			this.btnGestion.CanFocus = true;
			this.btnGestion.Name = "btnGestion";
			this.btnGestion.UseUnderline = true;
			this.btnGestion.Label = global::Mono.Unix.Catalog.GetString("Gestión de Empleados");
			this.vbox2.Add(this.btnGestion);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.btnGestion]));
			w1.Position = 0;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnCargos = new global::Gtk.Button();
			this.btnCargos.CanFocus = true;
			this.btnCargos.Name = "btnCargos";
			this.btnCargos.UseUnderline = true;
			this.btnCargos.Label = global::Mono.Unix.Catalog.GetString("Gestion de Cargos");
			this.hbox1.Add(this.btnCargos);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnCargos]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnDep = new global::Gtk.Button();
			this.btnDep.CanFocus = true;
			this.btnDep.Name = "btnDep";
			this.btnDep.UseUnderline = true;
			this.btnDep.Label = global::Mono.Unix.Catalog.GetString("Gestion de Departamentos");
			this.hbox1.Add(this.btnDep);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnDep]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnCarEmpleado = new global::Gtk.Button();
			this.btnCarEmpleado.CanFocus = true;
			this.btnCarEmpleado.Name = "btnCarEmpleado";
			this.btnCarEmpleado.UseUnderline = true;
			this.btnCarEmpleado.Label = global::Mono.Unix.Catalog.GetString("Asignar Cargos");
			this.hbox1.Add(this.btnCarEmpleado);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnCarEmpleado]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnReporte1 = new global::Gtk.Button();
			this.btnReporte1.CanFocus = true;
			this.btnReporte1.Name = "btnReporte1";
			this.btnReporte1.UseUnderline = true;
			this.btnReporte1.Label = global::Mono.Unix.Catalog.GetString("Reporte Empleados");
			this.vbox2.Add(this.btnReporte1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.btnReporte1]));
			w6.Position = 2;
			w6.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 464;
			this.DefaultHeight = 111;
			this.Show();
			this.btnGestion.Clicked += new global::System.EventHandler(this.OnBtnReporteClicked);
			this.btnCargos.Clicked += new global::System.EventHandler(this.OnBtnCargosClicked);
			this.btnDep.Clicked += new global::System.EventHandler(this.OnBtnDepClicked);
			this.btnCarEmpleado.Clicked += new global::System.EventHandler(this.OnBtnCarEmpleadoClicked);
		}
	}
}
