
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEmpleadosEyS
{
	public partial class GestionEmpleados
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.Label lbGestion;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Button btnAñadir;

		private global::Gtk.Button btnModificar;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Entry entryBuscar;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.HButtonBox hbuttonbox1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvEmpleado;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEmpleadosEyS.GestionEmpleados
			this.Name = "SistemaEmpleadosEyS.GestionEmpleados";
			this.Title = global::Mono.Unix.Catalog.GetString("GestionEmpleados");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SistemaEmpleadosEyS.GestionEmpleados.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lbGestion = new global::Gtk.Label();
			this.lbGestion.Name = "lbGestion";
			this.lbGestion.LabelProp = global::Mono.Unix.Catalog.GetString("Gestión de Datos");
			this.vbox4.Add(this.lbGestion);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.lbGestion]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btnAñadir = new global::Gtk.Button();
			this.btnAñadir.CanFocus = true;
			this.btnAñadir.Name = "btnAñadir";
			this.btnAñadir.UseUnderline = true;
			this.btnAñadir.Label = global::Mono.Unix.Catalog.GetString("Añadir");
			this.hbox5.Add(this.btnAñadir);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnAñadir]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btnModificar = new global::Gtk.Button();
			this.btnModificar.CanFocus = true;
			this.btnModificar.Name = "btnModificar";
			this.btnModificar.UseUnderline = true;
			this.btnModificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.hbox5.Add(this.btnModificar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnModificar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.hbox15.Add(this.btnEliminar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.btnEliminar]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.entryBuscar = new global::Gtk.Entry();
			this.entryBuscar.CanFocus = true;
			this.entryBuscar.Name = "entryBuscar";
			this.entryBuscar.IsEditable = true;
			this.entryBuscar.InvisibleChar = '•';
			this.hbox15.Add(this.entryBuscar);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.entryBuscar]));
			w5.Position = 1;
			// Container child hbox15.Gtk.Box+BoxChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox15.Add(this.btnBuscar);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.btnBuscar]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox5.Add(this.hbox15);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox15]));
			w7.Position = 2;
			this.vbox4.Add(this.hbox5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.vbox4.Add(this.hbuttonbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbuttonbox1]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvEmpleado = new global::Gtk.TreeView();
			this.tvEmpleado.CanFocus = true;
			this.tvEmpleado.Name = "tvEmpleado";
			this.GtkScrolledWindow.Add(this.tvEmpleado);
			this.hbox4.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.GtkScrolledWindow]));
			w11.Position = 0;
			this.vbox4.Add(this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
			w12.Position = 3;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 540;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
