
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEmpleadosEyS
{
	public partial class Entrada_y_Salida
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label lbFechaHora;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button btnEntrada;

		private global::Gtk.Button btnSalida;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEmpleadosEyS.Entrada_y_Salida
			this.Name = "SistemaEmpleadosEyS.Entrada_y_Salida";
			this.Title = global::Mono.Unix.Catalog.GetString("Entrada y Salida");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SistemaEmpleadosEyS.Entrada_y_Salida.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lbFechaHora = new global::Gtk.Label();
			this.lbFechaHora.Name = "lbFechaHora";
			this.lbFechaHora.LabelProp = global::Mono.Unix.Catalog.GetString("dd/mm/yyyy    hh:mm");
			this.hbox1.Add(this.lbFechaHora);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lbFechaHora]));
			w1.Position = 0;
			w1.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnEntrada = new global::Gtk.Button();
			this.btnEntrada.CanFocus = true;
			this.btnEntrada.Name = "btnEntrada";
			this.btnEntrada.UseUnderline = true;
			this.btnEntrada.Label = global::Mono.Unix.Catalog.GetString("Entrada");
			this.hbox2.Add(this.btnEntrada);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnEntrada]));
			w3.Position = 0;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnSalida = new global::Gtk.Button();
			this.btnSalida.CanFocus = true;
			this.btnSalida.Name = "btnSalida";
			this.btnSalida.UseUnderline = true;
			this.btnSalida.Label = global::Mono.Unix.Catalog.GetString("Salida");
			this.hbox2.Add(this.btnSalida);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnSalida]));
			w4.Position = 1;
			w4.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 63;
			this.Show();
		}
	}
}
